# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Cupcake.create([

  {
    name: "Unicorn",
    type: "Cupcake",
    calories: "131",
    carbs: "29g",
    description: "Vanilla funfetti sprinkle sponge. Raspberry jam filling. Vanilla Swiss buttercream. Unicorn Poop meringues. Edible glitter. Hundreds and thousands.",
    price: "$34.00",
    mini_price: "$17.00",
    image: "https://cupcakeshop.s3.amazonaws.com/unicorn-cupcakes_1280x1280%402x.jpg",
    image1: "https://cupcakeshop.s3.amazonaws.com/unicorn-cupcakes-4_1280x1280%402x.jpg",
    image2: "https://cupcakeshop.s3.amazonaws.com/unicorn-cupcakes-5_1280x1280%402x.jpg",
  },
  {
    name: "Jammy Dodger",
    type: "Cupcake",
    calories: "120",
    carbs: "23g",
    description: "Raspberry ripple vanilla sponge. Raspberry goo filling. Vanilla buttercream. Raspberry jam splodge. Jammy Dodger.",
    price: "$38.00",
    mini_price: "$19.00",
    image: "https://cupcakeshop.s3.amazonaws.com/jammy-dodger-cupcakes_1280x1280%402x.jpg",
    image1: "https://cupcakeshop.s3.amazonaws.com/jammy-dodger-cupcakes-4_1280x1280%402x.jpg",
    image2: "https://cupcakeshop.s3.amazonaws.com/jammy-dodger-cupcakes-5_1280x1280%402x.jpg",
  },
  {
    name: "Jammy Dodger",
    type: "Cupcake",
    calories: "120",
    carbs: "23g",
    description: "Raspberry ripple vanilla sponge. Raspberry goo filling. Vanilla buttercream. Raspberry jam splodge. Jammy Dodger.",
    price: "$38.00",
    mini_price: "$19.00",
    image: "https://cupcakeshop.s3.amazonaws.com/neapolitan-cupcakes-4_1280x1280%402x.jpg",
    image1: "https://cupcakeshop.s3.amazonaws.com/neapolitan-cupcakes-4_1280x1280%402x.jpg",
    image2: "https://cupcakeshop.s3.amazonaws.com/neapolitan-cupcakes-4_1280x1280%402x.jpg",
  },
  {
    name: "Eton Mess",
    type: "Cupcake",
    calories: "134",
    carbs: "24g",
    description: "Strawberry sponge. Fresh strawberry goo filling. Vanilla meringue crush buttercream. Raspberry goo drizzle.",
    price: "$34.00",
    mini_price: "$16.00",
    image: "https://cupcakeshop.s3.amazonaws.com/neapolitan-cupcakes-4_1280x1280%402x.jpg",
    image1: "https://cupcakeshop.s3.amazonaws.com/neapolitan-cupcakes-4_1280x1280%402x.jpg",
    image2: "https://cupcakeshop.s3.amazonaws.com/neapolitan-cupcakes-4_1280x1280%402x.jpg",
  },
  {
    name: "Neapolitan",
    type: "Cupcake",
    calories: "120",
    carbs: "21g",
    description: "Strawberry sponge. Fresh strawberry goo filling. Vanilla buttercream. Chocolate ganache. Hundreds & Thousands.",
    price: "$34.00",
    mini_price: "$18.00",
    image: "https://cupcakeshop.s3.amazonaws.com/neapolitan-cupcakes-4_1280x1280%402x.jpg",
    image1: "https://cupcakeshop.s3.amazonaws.com/neapolitan-cupcakes-4_1280x1280%402x.jpg",
    image2: "https://cupcakeshop.s3.amazonaws.com/neapolitan-cupcakes-4_1280x1280%402x.jpg",
  },
  {
    name: "Mint Choc Chip",
    type: "Cupcake",
    calories: "180",
    carbs: "25g",
    description: "Peppermint chocolate sponge. Peppermint buttercream. Peppermint Chocolate buttercream. Chocolate ganache drizzle.",
    price: "$34.00",
    mini_price: "$18.00",
    image: "https://cupcakeshop.s3.amazonaws.com/mint-choc-chip-cupcakes-4_1280x1280%402x.jpg",
    image1: "https://cupcakeshop.s3.amazonaws.com/mint-choc-chip-cupcakes-4_1280x1280%402x.jpg",
    image2: "https://cupcakeshop.s3.amazonaws.com/mint-choc-chip-cupcakes-4_1280x1280%402x.jpg",
  },
  {
    name: "Lemon Meringue Pie",
    type: "Cupcake",
    calories: "140",
    carbs: "22g",
    description: "Lemon sponge. Freshly-made lemon curd filling. Lemon buttercream icing. Crushed meringues. Lemon curd. Pie crumb.",
    price: "$38.00",
    mini_price: "$19.00",
    image: "https://cupcakeshop.s3.amazonaws.com/biscoff-cupcakes-5_1280x1280%402x.jpg",
    image1: "https://cupcakeshop.s3.amazonaws.com/biscoff-cupcakes-5_1280x1280%402x.jpg",
    image2: "https://cupcakeshop.s3.amazonaws.com/biscoff-cupcakes-5_1280x1280%402x.jpg",
  },
  {
    name: "Biscoff",
    type: "Cupcake",
    calories: "130",
    carbs: "22g",
    description: "Buttery biscoff biscuit base. Brown sugar sponge. Whipped biscoff cream filling. Biscoff Swiss meringue buttercream frosting. Biscoff spread drizzle. Lotus biscuit decoration.",
    price: "$38.00",
    mini_price: "$17.00",
    image: "https://cupcakeshop.s3.amazonaws.com/biscoff-cupcakes-2_1280x1280%402x.jpg",
    image1: "https://cupcakeshop.s3.amazonaws.com/Biscoff-Cupcake_1280x1280%402x.jpg",
    image2: "https://cupcakeshop.s3.amazonaws.com/biscoff-cupcakes-5_1280x1280%402x.jpg",
  },
  {
    name: "Cookies & Cream",
    type: "Cupcake",
    calories: "160",
    carbs: "23g",
    description: "Chocolate sponge. Whipped Chantilly cream filling. Oreo crumb buttercream frosting. Chocolate ganache drizzle. Oreo chunks.",
    price: "$38.00",
    mini_price: "$17.00",
    image: "https://cupcakeshop.s3.amazonaws.com/Bourbon_Biscuit_Cupcake_NB_1_1280x1280%402x.jpg",
    image1: "https://cupcakeshop.s3.amazonaws.com/Bourbon_Biscuit_Cupcake_NB_1_1280x1280%402x.jpg",
    image2: "https://cupcakeshop.s3.amazonaws.com/Bourbon_Biscuit_Cupcake_NB_1_1280x1280%402x.jpg",
  },
  {
    name: "Bourbon Biscuit",
    type: "Cupcake",
    calories: "160",
    carbs: "24g",
    description: "Malted cocoa sponge. Chocolate whipped cream filling. Swiss meringue chocolate buttercream. Bourbon biscuit decoration.",
    price: "$38.00",
    mini_price: "$17.00",
    image: "https://cupcakeshop.s3.amazonaws.com/Bourbon_Biscuit_Cupcake_NB_1_1280x1280%402x.jpg",
    image1: "https://cupcakeshop.s3.amazonaws.com/Bourbon_Biscuit_Cupcake_nb_4_1280x1280%402x.jpg",
    image2: "https://cupcakeshop.s3.amazonaws.com/Bourbon_Biscuit_Cupcake_nb_5_1280x1280%402x.jpg",
  },
  {
    name: "Ferrero Rocher",
    type: "Cupcake",
    calories: "190",
    carbs: "25g",
    description: "Cocoa and gianduja hazelnut sponge. Hazelnut cream filling. Hazelnut buttercream. Chocolate dunk. Chopped toasted hazelnuts.",
    price: "$38.00",
    mini_price: "$19.00",
    image: "https://cupcakeshop.s3.amazonaws.com/caramel-rolo-cupcakes-4_1280x1280%402x.jpg",
    image1: "https://cupcakeshop.s3.amazonaws.com/caramel-rolo-cupcakes-4_1280x1280%402x.jpg",
    image2: "https://cupcakeshop.s3.amazonaws.com/caramel-rolo-cupcakes-4_1280x1280%402x.jpg",
  },
  {
    name: "Caramel Rolo",
    type: "Cupcake",
    calories: "190",
    carbs: "22g",
    description: "Chocolate sponge. Caramel filling. Caramel buttercream icing. Chocolate drizzle. Rolos.",
    price: "$38.00",
    mini_price: "$17.00",
    image: "",
    image1: "",
    image2: "",
  },
  {
    name: "Raspberry Bombe",
    type: "Cupcake",
    calories: "200",
    carbs: "23g",
    description: "Dark Callebaut chocolate sponge. Fresh raspberry goo filling. Raspberry buttercream. Raspberry goo drizzle. Crushed meringue.",
    price: "$38.00",
    mini_price: "$17.00",
    image: "https://cupcakeshop.s3.amazonaws.com/malteser-cupcakes_1280x1280%402x.jpg",
    image1: "https://cupcakeshop.s3.amazonaws.com/malteser-cupcakes_1280x1280%402x.jpg",
    image2: "https://cupcakeshop.s3.amazonaws.com/malteser-cupcakes_1280x1280%402x.jpg",
  },
  {
    name: "Malteser",
    type: "Cupcake",
    calories: "130",
    carbs: "19g",
    description: "Malted cocoa sponge. Malteser crumb buttercream. Maltesers.",
    price: "$30.00",
    mini_price: "$16.00",
    image: "https://cupcakeshop.s3.amazonaws.com/malteser-cupcakes_1280x1280%402x.jpg",
    image1: "https://cupcakeshop.s3.amazonaws.com/malteser-cupcakes-4_1280x1280%402x.jpg",
    image2: "https://cupcakeshop.s3.amazonaws.com/malteser-cupcakes-4_1280x1280%402x.jpg",

  },
  {
    name: "Vanilla",
    type: "Cupcake",
    calories: "130",
    carbs: "19g",
    description: "Vanilla sponge. Vanilla buttercream in your choice of colour. Sprinkles.",
    price: "$28.00",
    mini_price: "$14.00",
    image: "https://cupcakeshop.s3.amazonaws.com/vanilla-cupcakes_1280x1280%402x.jpg",
    image1: "https://cupcakeshop.s3.amazonaws.com/vanilla-cupcakes-4_1280x1280%402x.jpg",
    image2: "https://cupcakeshop.s3.amazonaws.com/vanilla-cupcakes-5_1280x1280%402x.jpg",
  },
  {
    name: "Velvet Volcano",
    type: "Cupcake",
    calories: "180",
    carbs: "22g",
    description: "Buttery biscuit base. Red velvet sponge. Baked-in cookie dough. Oreo crumb buttercream. Chocolate ganache drizzle. Salted caramel drizzle.",
    price: "$38.00",
    mini_price: "$17.00",
    image: "https://cupcakeshop.s3.amazonaws.com/velvet-volcano-cupcakes-5_1280x1280%402x.jpg",
    image1: "https://cupcakeshop.s3.amazonaws.com/sprinkle-cupcakes-4_1280x1280%402x.jpg",
    image2: "https://cupcakeshop.s3.amazonaws.com/velvet-volcano-cupcakes-5_1280x1280%402x.jpg",
  },
  {
    name: "Caramel Pretzel",
    type: "Cupcake",
    calories: "170",
    carbs: "21g",
    description: "Callebaut Chocolate sponge. Salted caramel buttercream frosting. Caramel drizzle. Pretzels.",
    price: "$30.00",
    mini_price: "$15.00",
    image: "https://cupcakeshop.s3.amazonaws.com/caramel-pretzel-cupcakes_1280x1280%402x.jpg",
    image1: "https://cupcakeshop.s3.amazonaws.com/caramel-pretzel-cupcakes-4_1280x1280%402x.jpg",
    image2: "https://cupcakeshop.s3.amazonaws.com/caramel-pretzel-cupcakes-5_1280x1280%402x.jpg",
  },
  {
    name: "Sprinkle",
    type: "Cupcake",
    calories: "140",
    carbs: "19g",
    description: "Vanilla Sprinkle funfetti vanilla sponge. Vanilla buttercream. Hundreds & Thousands.",
    price: "$30.00",
    mini_price: "$15.00",
    image: "https://cupcakeshop.s3.amazonaws.com/sprinkle-cupcakes-4_1280x1280%402x.jpg",
    image1: "https://cupcakeshop.s3.amazonaws.com/sprinkle-cupcakes-4_1280x1280%402x.jpg",
    image2: "https://cupcakeshop.s3.amazonaws.com/sprinkle-cupcakes-4_1280x1280%402x.jpg",
  },
  {
    name: "Bounty",
    type: "Cupcake",
    calories: "210",
    carbs: "23g",
    description: "Chocolate sponge. Coconut Cream filling. Coconut buttercream. Chocolate Ganache drizzle. Dessicated Coconut.",
    price: "$38.00",
    mini_price: "$15.00",
    image: "https://cupcakeshop.s3.amazonaws.com/bounty-cupcakes_1280x1280%402x.jpg",
    image1: "https://cupcakeshop.s3.amazonaws.com/bounty-cupcakes-4_1280x1280%402x.jpg",
    image2: "https://cupcakeshop.s3.amazonaws.com/bounty-cupcakes-5_1280x1280%402x.jpg",
  },
  {
    name: "Pastel Swirl",
    type: "Cupcake",
    calories: "180",
    carbs: "22g",
    description: "Vanilla sponge. Triple pastel swirled vanilla buttercream.",
    price: "$35.00",
    mini_price: "$17.00",
    image: "https://cupcakeshop.s3.amazonaws.com/triple-chocolate-cupcakes-5_1280x1280%402x.jpg",
    image1: "https://cupcakeshop.s3.amazonaws.com/triple-chocolate-cupcakes-4_1280x1280%402x.jpg",
    image2: "https://cupcakeshop.s3.amazonaws.com/triple-chocolate-cupcakes-5_1280x1280%402x.jpg",
  },
  {
    name: "Triple Chocolate",
    type: "Cupcake",
    calories: "200",
    carbs: "22g",
    description: "Chocolate sponge. Chocolate cream cheese icing. Chocolate ganache drizzle.",
    price: "$30.00",
    mini_price: "$15.00",
    image: "",
    image1: "",
    image2: "",
  },
  {
    name: "Salted Caramel",
    type: "Cupcake",
    calories: "210",
    carbs: "24g",
    description: "Brown sugar sponge. Salted caramel buttercream icing. Caramel drizzle.",
    price: "$30.00",
    mini_price: "$15.00",
    image: "https://cupcakeshop.s3.amazonaws.com/salted-caramel-cupcakes_1280x1280%402x.jpg",
    image1: "https://cupcakeshop.s3.amazonaws.com/salted-caramel-cupcakes-4_1280x1280%402x.jpg",
    image2: "https://cupcakeshop.s3.amazonaws.com/salted-caramel-cupcakes-5_1280x1280%402x.jpg",
  },
  {
    name: "Cookie Dough",
    type: "Cupcake",
    calories: "190",
    carbs: "21g",
    description: "Chocolate chip burnt butter sponge with a chunk of cookie dough baked in. Topped with vanilla buttercream and cookie dough.",
    price: "$34.00",
    mini_price: "$18.00",
    image: "https://cupcakeshop.s3.amazonaws.com/cookie-dough-cupcakes_1280x1280%402x.jpg",
    image1: "https://cupcakeshop.s3.amazonaws.com/cookie-dough-cupcakes-4_1280x1280%402x.jpg",
    image2: "https://cupcakeshop.s3.amazonaws.com/cookie-dough-cupcakes-5_1280x1280%402x.jpg",
  },
  {
    name: "Chocolate Guinness",
    type: "Cupcake",
    calories: "190",
    carbs: "22g",
    description: "Chocolate Guinness sponge. Cream cheese and Chocolate cream cheese icing.",
    price: "$30.00",
    mini_price: "$15.00",
    image: "https://cupcakeshop.s3.amazonaws.com/chocolate-guinness-cupcakes_1280x1280%402x.jpg",
    image1: "https://cupcakeshop.s3.amazonaws.com/chocolate-guinness-cupcakes-4_1280x1280%402x.jpg",
    image2: "https://cupcakeshop.s3.amazonaws.com/chocolate-guinness-cupcakes-4_1280x1280%402x.jpg",
  },
  {
    name: "Lemon & Poppyseed",
    type: "Cupcake",
    calories: "170",
    carbs: "21g",
    description: "Lemon and Poppyseed sponge. Cream cheese frosting. Poppyseeds.",
    price: "$30.00",
    mini_price: "$15.00",
    image: "https://cupcakeshop.s3.amazonaws.com/lemon-poppyseed-cupcakes_1280x1280%402x.jpg",
    image1: "https://cupcakeshop.s3.amazonaws.com/lemon-poppyseed-cupcakes-4_1280x1280%402x.jpg",
    image2: "https://cupcakeshop.s3.amazonaws.com/lemon-poppyseed-cupcakes-5_1280x1280%402x.jpg",
  },
  {
    name: "Raspberry Ripple",
    type: "Cupcake",
    calories: "190",
    carbs: "22g",
    description: "Raspberry-rippled Vanilla sponge. Vanilla and fresh raspberry buttercream icing.",
    price: "$30.00",
    mini_price: "$15.00",
    image: "https://cupcakeshop.s3.amazonaws.com/raspberry-ripple-cupcakes_1280x1280%402x.jpg",
    image1: "https://cupcakeshop.s3.amazonaws.com/raspberry-ripple-cupcakes-4_1280x1280%402x.jpg",
    image2: "https://cupcakeshop.s3.amazonaws.com/raspberry-ripple-cupcakes-5_1280x1280%402x.jpg",
  },
  {
    name: "Carrot",
    type: "Cupcake",
    calories: "190",
    carbs: "22g",
    description: "Spiced carrot and walnut sponge. Cream cheese frosting. Walnut.",
    price: "$38.00",
    mini_price: "$17.00",
    image: "https://cupcakeshop.s3.amazonaws.com/carrot-cupcakes_1280x1280%402x.jpg",
    image1: "https://cupcakeshop.s3.amazonaws.com/carrot-cupcakes-4_1280x1280%402x.jpg",
    image2: "https://cupcakeshop.s3.amazonaws.com/carrot-cupcakes-5_1280x1280%402x.jpg",
  },
  {
    name: "Cinnamon Toast",
    type: "Cupcake",
    calories: "220",
    carbs: "22g",
    description: "Wholemeal toast crumb cinnamon sponge. Cinnamon buttercream. Buttered toast crumb. Cinnamon sugar.",
    price: "$34.00",
    mini_price: "$17.00",
    image: "https://cupcakeshop.s3.amazonaws.com/cinnamon-toast-cupcakes_1280x1280%402x.jpg",
    image1: "https://cupcakeshop.s3.amazonaws.com/cinnamon-toast-cupcakes-4_1280x1280%402x.jpg",
    image2: "https://cupcakeshop.s3.amazonaws.com/cinnamon-toast-cupcakes-5_1280x1280%402x.jpg",
  },
  {
    name: "English Breakfast",
    type: "Cupcake",
    calories: "210",
    carbs: "23g",
    description: "Earl grey infused sponge. Marmalade filling. Earl grey buttercream. Marmalade drizzle. Buttery toast crumb sprinkle.",
    price: "$38.00",
    mini_price: "$19.00",
    image: "https://cupcakeshop.s3.amazonaws.com/english-breakfast-cupcakes_1280x1280%402x.jpg",
    image1: "https://cupcakeshop.s3.amazonaws.com/english-breakfast-cupcakes-4_1280x1280%402x.jpg",
    image2: "https://cupcakeshop.s3.amazonaws.com/english-breakfast-cupcakes-5_1280x1280%402x.jpg",
  },
  {
    name: "Red Velvet",
    type: "Cupcake",
    calories: "230",
    carbs: "25g",
    description: "Red Velvet sponge. Dairy-free vanilla frosting. Red Velvet crumb.",
    price: "$30.00",
    mini_price: "$14.00",
    image: "https://cupcakeshop.s3.amazonaws.com/vegan-red-velvet-cupcakes_1280x1280%402x.jpg",
    image1: "https://cupcakeshop.s3.amazonaws.com/vegan-red-velvet-cupcakes-4_1280x1280%402x.jpg",
    image2: "https://cupcakeshop.s3.amazonaws.com/vegan-red-velvet-cupcakes-5_1280x1280%402x.jpg",
  },
  {
    name: "Matcha White Chocolate",
    type: "Cupcake",
    calories: "180",
    carbs: "22g",
    description: "Green Tea Matcha sponge. Matcha white chocolate cream filling. White chocolate buttercream. White chocolate matcha drizzle.",
    price: "$38.00",
    mini_price: "$19.00",
    image: "https://cupcakeshop.s3.amazonaws.com/matcha-white-chocolate-cupcakes_1280x1280%402x.jpg",
    image1: "https://cupcakeshop.s3.amazonaws.com/matcha-white-chocolate-cupcakes-4_1280x1280%402x.jpg",
    image2: "https://cupcakeshop.s3.amazonaws.com/matcha-white-chocolate-cupcakes-5_1280x1280%402x.jpg",
  },
  {
    name: "Mocha",
    type: "Cupcake",
    calories: "200",
    carbs: "25g",
    description: "Classic Callebaut chocolate sponge. Espresso coffee buttercream. Chocolate ganache drizzle. Coffee chocolate crumb.",
    price: "$34.00",
    mini_price: "$17.00",
    image: "https://cupcakeshop.s3.amazonaws.com/coffee-chocolate-cupcakes_1280x1280%402x.jpg",
    image1: "https://cupcakeshop.s3.amazonaws.com/coffee-chocolate-cupcakes-4_1280x1280%402x.jpg",
    image2: "https://cupcakeshop.s3.amazonaws.com/coffee-chocolate-cupcakes-5_1280x1280%402x.jpg",
  },
  {
    name: "Sesame White Chocolate",
    type: "Cupcake",
    calories: "240",
    carbs: "25g",
    description: "White chocolate mud cake sponge. White chocolate filling. Toasted Black Sesame Swiss meringue buttercream. White chocolate drizzle. Crystallised toasted black sesames.",
    price: "$38.00",
    mini_price: "$20.00",
    image: "https://cupcakeshop.s3.amazonaws.com/sesame-white-chocolate-cupcakes_1280x1280%402x.jpg",
    image1: "https://cupcakeshop.s3.amazonaws.com/sesame-white-chocolate-cupcakes-4_1280x1280%402x.jpg",
    image2: "https://cupcakeshop.s3.amazonaws.com/sesame-white-chocolate-cupcakes-5_1280x1280%402x.jpg",
  },
  {
    name: "Rose & Pistachio",
    type: "Cupcake",
    calories: "210",
    carbs: "23g",
    description: "Pistachio sponge. Whipped pistachio cream filling. Vanilla rose buttercream. Crystallised rose petals. Pistachios.",
    price: "$34.00",
    mini_price: "$17.00",
    image: "https://cupcakeshop.s3.amazonaws.com/rose-pistachio-cupcakes-2_1280x1280%402x.jpg",
    image1: "https://cupcakeshop.s3.amazonaws.com/rose-pistachio-cupcakes_1280x1280%402x.jpg",
    image2: "https://cupcakeshop.s3.amazonaws.com/rose-pistachio-cupcakes-5_1280x1280%402x.jpg",
  },
  {
    name: "Snickers",
    type: "Cupcake",
    calories: "180",
    carbs: "21g",
    description: "Chocolate sponge. Whipped peanougat filling. Salted caramel buttercream. Chocolate ganache. Caramel drizzle. Chopped roasted peanuts.",
    price: "$38.00",
    mini_price: "$19.00",
    image: "https://cupcakeshop.s3.amazonaws.com/snickers-cupcakes_1280x1280%402x.jpg",
    image1: "https://cupcakeshop.s3.amazonaws.com/snickers-cupcakes-4_1280x1280%402x.jpg",
    image2: "https://cupcakeshop.s3.amazonaws.com/snickers-cupcakes-5_1280x1280%402x.jpg",
  },
  {
    name: "Velvet & Cookie",
    type: "Cupcake",
    calories: "240",
    carbs: "25g",
    description: "Dairy-free Red Velvet sponge. Oreo cookie dairy free icing. Vegan chocolate drizzle. Oreo cookie chunks.",
    price: "$38.00",
    mini_price: "$20.00",
    image: "https://cupcakeshop.s3.amazonaws.com/190326-crumbsanddoilies16154_1280x1280%402x.jpg",
    image1: "https://cupcakeshop.s3.amazonaws.com/190326-crumbsanddoilies16157_1280x1280%402x.jpg",
    image2: "https://cupcakeshop.s3.amazonaws.com/190326-crumbsanddoilies16177_1280x1280%402x.jpghttps://cupcakeshop.s3.amazonaws.com/Biscoff-Cupcake_1280x1280%402x.jpg",
  },

  ])
